name: "$(Date:yyyy).$(Date:MM).$(Rev:r)"

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - src/*
    - tests/*
    - prisma/*


pool:
  vmImage: ubuntu-latest

jobs:
- job:
  displayName: Build
  steps:

  - task: CmdLine@2
    displayName: 'List files'
    inputs:
      script: mv $(Build.SourcesDirectory)/.env.example $(Build.SourcesDirectory)/.env
  
  - task: DockerCompose@0
    displayName: Run Docker-compose-up
    inputs:
      containerregistrytype: Container Registry
      dockerComposeFile: $(Build.SourcesDirectory)/docker-compose.yaml
      dockerComposeCommand: 'up -d'

  - task: CmdLine@2
    displayName: 'Curl'
    inputs:
      script: curl http://localhost:3000/health


  - task: CmdLine@2
    displayName: 'Curl'
    inputs:
      script: curl http://localhost:3000/health
  
  - task: UseNode@1
    inputs:
      version: '20.x'
      checkLatest: true

  - task: Npm@0
    displayName: Run NPM Update for NestJS
    inputs:
      cwd: '$(Build.SourcesDirectory)/.'
      command: update

  - task: Npm@0
    displayName: Build
    inputs:
      cwd: '$(Build.SourcesDirectory)/.'
      command: build start

  - task: Npm@0
    displayName: run test
    inputs:
      cwd: '$(Build.SourcesDirectory)/.'
      command: run test e2e